name: ethio_fm_radio
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.2.1
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1
  path_provider: ^2.1.5
  flutter_screenutil: ^5.9.3
  audioplayers: ^6.5.0
  http: ^1.4.0
  just_audio: ^0.10.4
  rxdart: ^0.28.0
  cached_network_image: ^3.4.1
  just_audio_background: ^0.0.1-beta.17
  audio_video_progress_bar: ^2.0.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  flutter_bloc: ^9.1.1
  permission_handler: ^12.0.1
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/audio/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
